# Generated by Django 3.2.7 on 2021-09-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_post_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currentCount',
            field=models.IntegerField(default=0),
        ),
    ]
